:experimental:

== Planning

Although Scrivener is a _writing_ tool, it’s also a _planning_ tool. These two activities hold equal importance here in Scrivener Land. Maybe you’re a pantser — that’s someone who writes by the seat of their pants, hoping for inspiration. You haven’t the faintest idea what you’re going to write until you see it. A kinder term is _discovery writer_. Even if that’s you, you’ll make it easier for yourself if you use at least a few of the features I’ll show you in this chapter. If you’re a planner, you’ll be in heaven.

First, we’ll set up your Research Folder. This is where you stash the material you  refer to while writing. As I’ll show you, it’s easy to display journal articles, images, or even videos alongside your writing. Once you’ve got everything you need, you can focus on generating those words.

Then we’ll return to the Corkboard. In the previous chapter, we used the Corkboard to view existing documents. This time, we’ll create a storyboard and experiment with different sequences. The Corkboard is especially good for visual thinkers.

If you prefer a more detailed approach, the Outliner is for you. We’ll create a structure or wireframe for your Project and also display important information, such as the word count.

In a thesis, we often employ a repetitive structure, especially in areas such as the literature review and in case studies. I’ll show you how to create reusable templates. These will save you time, ensure consistency, and also provide prompts when you’re lacking inspiration.

There are lots of ways to monitor your progress in Scrivener. In this chapter, we’ll look at two: word targets and status. You’ll notice that Scrivener is both a writing tool and a project management tool. Once you’ve set up some targets, you can quickly see what’s left to do.

Let’s make a plan.