:experimental:

=== Adding Metadata

As I mentioned earlier, metadata is data about your document. You’ve already used metadata for flagging the Status in the bottom right-hand corner of Scrivener. Now you’ll learn about two more types of metadata: labels and keywords. 

==== Labels

If you have a lot of documents, it’s useful to group them together in different ways. In other tools, such as Zotero and Evernote, you use tags to create these links. In Scrivener, we have _labels_.

We’ve already used some labels when setting the _status_ for each document, such as To Do, First Draft, and so on. You can create other types of label, too. 

At the bottom of the Inspector, you’ll see _No Label_ next to the Status of your document. If you click on it, you’ll get the option to apply a coloured label. You can either use one of the preset colours, or create your own. 

[screenshot: Label — show Edit ]

Click *Edit* at the bottom of the Label list and you’ll get a pop-up window. You can then change the names of each colour by clicking on them and change the colour, too. With the plus and minus icons, you can add or remove labels.

[screenshot: Labels window ]

You can use these labels in any way you like. Perhaps you could assign a difficulty level to a document or an estimate for how long you think it might take to write. It could also be useful for labelling different parts of your project, e.g. methodology, discussion, theory. There’s no need to use this feature at all, if you don’t want to.

I use labels to flag my confidence level with completed documents:

	* Green = this is OK.
	* Amber =  it would probably benefit from a few tweaks.
	* Red = I still have some concerns.

Like Status, you can also use Labels within the Research Folder.

===== Displaying Labels

Once you’re using labels, you can choose to display them in various places. On the top menu, click *View > Use Label Color In*. If you select Binder, you now get a coloured blob next to that document in the Binder. For Corkboard, you’ll get a coloured line on your index card for that document.

[screenshot: label in Binder; label in Corkboard ]

Labels are usually displayed by default in the Outliner. If they’re not visible, you can click the arrow and check the box for Labels.

[screenshot: label in Outliner  ]

Like icons, labels provide helpful visual cues for navigating your project.

===== Arranging by Label

You can also use labels to _arrange_ or sort your index cards in the Corkboard. If you click the *Arrange by Label* icon at the bottom of the Corkboard, your cards are arranged on different lines, according to the label colour. You can even change a card’s label by clicking and dragging it to another line.

[screenshot: Arrange by Label — make sure icon is visible — magnify it, too? ]

This feature is useful if you want to sort your documents by theme or topic. Perhaps you have a folder of separate documents in which you’ve written about specific journal articles. Now you want to organize these documents to assemble your literature review. Here’s how it might work.

	* First create your Labels in Project Settings (*Project > Project Settings > Label List*).

[screenshot: Label List in Project Settings ]

	* Now open your group of documents in Corkboard View (remember, they all need to be subdocuments of the same document to use a Group Mode, such as the Corkboard or Outliner.

[screenshot: Show Corkboard with folder selected ]

	* Click the Arrange by Label icon at the bottom of the Corkboard.

[screenshot: show Arrange by Label icon ]

	* Then you’ll see the corresponding coloured lines in Arrange by Label mode. Hover over the lines to see the Label name.

If you prefer, you can view the Label lines vertically in columns.

[screenshot: show arrange vertically icon ]

	* Now you can arrange your documents by dragging them to the appropriate coloured line.

This action doesn’t change the Binder structure. By moving the documents, you’re only assigning a label.

To give yourself more space when using this feature, you can hide the Binder (kbd:[option + cmd + b]) and Inspector (kbd:[option + cmd + i]). Use the same keyboard shortcuts to show the Binder and Inspector again. Or click the Layouts icon and choose *Corkboard Only*.

[screenshot: Show Layouts icon in toolbar ]

You can apply only one label to each document. To add multiple terms, you’ll need keywords.

==== Keywords

Keywords are another type of metadata you can associate with your documents. They’re useful for both classifying and searching. Keywords aren’t as visible as labels, but they’re more flexible. You can add multiple keywords to documents and also create hierarchies or taxonomies. If the idea of taxonomies is making you nervous, you can skip to the section on Searching [SIGNPOST].

===== Adding a Keyword

To add a keyword, click on the Metadata tab in the Inspector. It’s the icon that looks like a luggage label or tag. Now click the plus sign next to *Keywords* and enter your word. It’s added to the list, along with a coloured blob. You can change the colour of the blob by double-clicking it. 

[screenshot: Keywords & Label, show plus, minus, and ellipsis ]

If you click on the ellipsis and choose *Show Project Keywords*, you get a popup window with more options. Now you can create taxonomies, or hierarchies of keywords. For example, here I have the keyword Marriage. I select it in the keywords window, then click the *Add New Keyword as Child* icon at the bottom.

[screenshot: keyword window and show icon ]

To remove a keyword, select it and click the minus sign.

To create additional keywords, click the *Add New Keyword as Sibling* icon. This new keyword then appears at the same level in the hierarchy.

[screenshot: Show finished hierarchy, with Marriage, Employment, Leisure ]

From this window, you can also apply those keywords to other documents. First, select those documents in the Binder (hold down the cmd key as you click). Then select the keyword in the Keyword window and click the ellipsis in the bottom right-hand corner and choose *Apply Keywords to Selected Documents*.

[screenshot: Apply Keywords to Selected Documents ]

===== Searching with Keywords 

If you want to quickly find other documents with the same keyword, select the keyword in the list (press kbd:[shift + cmd + k] to display the Project Keywords), then click the tiny magnifying glass in the bottom right-hand corner. You’ll now see a Search Results pane instead of your Binder. To remove this pane, click the *x* in the top left-hand corner.

[screenshot: keyword search results pane + highlight x sign ]

This feature is incredibly powerful once your thesis grows to monster proportions. You’ll never remember where you mentioned specific people, theories, or concepts. With keywords, you can flag all those instances and quickly find them again. For example, if you decided to remove a specific case study, you could find all mentions through a keyword search and then edit those documents. That would be so much faster than having to read through the entire thesis. 

As with Status, you can also apply labels and keywords to anything in your Research Folder. Labels might be useful for flagging areas such as theory, methodology, or discussion. Keywords could help with simple coding, for example applying themes to interviews.

You can view your keyword blobs on the Corkboard, through *View > Corkboard Options > Show Keyword Colors* and also on the Outliner through *View > Outliner Options*. This is less helpful, I think, than the label blobs. You could easily amass dozens of keywords and you’re unlikely to remember their corresponding colours. I think labels are better for visual cues and keywords are better for searching and organizing.

It’s also possible to create your own Custom Metadata. First, though, I’ll show you the search features in Scrivener, as that’ll help you understand the advantages.