== Compiling and Exporting

If Snapshots are my favorite feature in Scrivener, Compiling and Exporting is my least favorite. I understand the developers wanted to add lots of flexibility and functionality, but I think it’s unnecessarily complicated, especially for new users. I’m an old user, but I still feel a bit sweaty every time I need to get something out of Scrivener. Consequently, I’m only going to show you simple examples in this chapter. Once you thoroughly understand the basics, you’ll be able to attempt some more sophisticated approaches.

You can output your Project in different ways, such as Word document, PDF, or EPUB (for ebooks). The content in Scrivener stays the same, it's just presented in another format. This is why the formatting features we saw earlier were fairly basic. Scrivener wants you to focus on _writing_ and then decide on the presentation at the end.

While this is a laudable sentiment, it does give you a potential headache right at the end of your PhD, when you're probably tired and grumpy. It’s a good idea, then, to at least familiarize yourself with this process well before you actually need to use it. You don’t want to be fathoming it when you’re up against a deadline.

Although you _could_ use Scrivener to produce a submission-ready version of your thesis, I’d recommend outputting it as a Word document and making your final tweaks there. I think you'll find it easier to conform to your university's formatting requirements.

In this chapter, I'll guide you through the process of getting your thesis out of Scrivener and into a format you can share with others. We'll start with printing as a warm-up, before moving on to structuring your thesis, and then compiling it into a different format. I recommend getting yourself a cup of coffee. And a biscuit.

=== Tidying Your Project

First, have a tidy up. Make sure any research material is in the Research Folder and that any odd documents have been deleted or safely parked in a separate folder. You don't want random notes or duplicate documents appearing in your final thesis. Also, check that all your documents have proper and consistent names. That'll make it easier for you to check that everything's in the right place. 

If there's anything that shouldn't be in your thesis but you don't want to lose, stash that content in a separate folder. In a moment, I'll show you how to exclude specific folders from your final thesis.
