:experimental:

=== Organizing the Structure

The Compilation process is much easier if you’ve organized your Binder using a proper hierarchy. Although we’ve already created sub-documents and folders in the Binder, this is purely visual. We haven’t told Scrivener what role each of these documents is performing when we export the project. 

We need to specify section types, such as chapters, sections, and sub-sections. Scrivener can then get a sense of the layout you want, for example, a page break before every new chapter. At the compilation stage, you can also specify certain formatting for different section types.  Spending some time on this now will prevent a lot of shouting later on. 

==== Creating Section Types

Sections are managed under *Project >  Project Settings > Section Types*.

kbd:[option + cmd + ,]

Here you can make a list of the different Section Types you want. This might be chapter, section, and sub-section. You can add or remove them using the plus and minus signs at the bottom. And click and drag to change the order.

[screenshot: Project > Project Settings > Section Types + show types for front and back matter]

You’ll also need Section Types for any front and back matter you’ve created, such as a title page or bibliography.

You can come back and change them at any time.

Once that’s done, you can assign those Section Types to the hierarchy of your Scrivener Binder.

Click *Default Types by Structure* in the Section Types dialogue box. Here you can decide that anything that’s a folder should be a Chapter. Anything that’s a main document with sub-documents is a Section. All other files, you can set as sub-sections. As you click on these Default Types, you’ll see the corresponding files in the Binder are highlighted in yellow.

Make sure your Binder is fully expanded (kbd:[cmd + 9]) so you can see what’s happening.

[screenshot: Default Types + highlighted documents in Binder + show icons for adding deeper levels]

If you need to, you can add additional levels with the plus sign at the bottom of the window. For instance, you might have sub-sub-documents to which you want to apply a different layout.

Now click *OK*.

==== Adding Section Types Manually

Default Types is the quickest way to specify Section Types, but you can also assign them on individual documents. You’ll find a document’s Section Type under the Metadata tab of the Inspector.

[screenshot: Section Type in Inspector ]

You can either let Scrivener default to Structure-Based section types, or override it with your own choice here.

Alternatively, you can assign Section Types in the Outliner. Make sure the Section Type column is visible, then use the dropdown list to assign a section.

[screenshot: Section Type in the Outliner ]

To change the Section Type for multiple documents, select them in the Outliner by holding down the cmd key as you click. Then click the dropdown list to choose a Section Type.

[screenshot: Assigning Section Types to multiple documents in the Outliner ]

You can also search by Section Type in Project Search [SIGNPOST].

In a moment, we’ll tell Scrivener how to present these different Section Types.