// Have decided to ditch this section - boring to write and boring to read!


== Configuring Settings

I won't go through _all_ the settings, as that would probably send you into a coma. I'm just going to draw your attention to them. Once you've been using Scrivener for a few months, you can come back and experiment with changing settings to optimize your experience.

To access your Scrivener preferences, press kbd:[cmd + ,].

Here you'll see seven tabs. 

// screenshot

=== General

This includes your auto-save and language preferences. It's also where you link your bibliography manager and specify the location for saving your Scratchpad files.

=== Editing

The main settings you want here are under the *Formatting* tab. This is where you configure your text formatting within Scrivener.

=== Behaviors

The settings here determine how the Scrivener interface behaves, such as what happens when you click and drag files or folders. I've never felt the need to change anything here.


=== Appearance

If you're finding the Scrivener interface hard to read, it's worth spending some time in this tab. Here you can change the font, colors, and spacing for the various elements, such as the Corkboard, notes, and progress bars.


=== Corrections

Sometimes it's helpful when Scrivener auto-corrects your typing, but maybe it's interfering with your formatting. Under the Corrections tab, you can decide what Scrivener is allowed to do. From here, you can also access your System Text Preferences for adding more sophisticated auto-corrections.


=== Sharing

If you're frequently importing documents into Scrivener, you can save some time by configuring the settings under the Import tab. This determines what happens with comments, footnotes, and styles.

=== Backup

We investigated the backup settings at the beginning of the book. This is another opportunity for me to remind you about the importance of backing up your work. Take a peek at these settings to make sure your Projects are backed up to the right place.


=== Restoring the Default Settings

If you've got carried away and made a flurry of regrettable changes, you can click Defaults to restore the original settings. As the warning message says, this action cannot be undone. Make sure you've noted any helpful changes before resetting.

// screenshot

=== Using Different Preferences in Projects

Maybe you want different Preferences in different Projects, or you're sharing Scrivener with someone else. In that case, you can save those preferences as a _Preset_. Once you've configured those Preferences, click *Manage* in the bottom left-hand corner of the window, then choose *Save Preferences as Preset*. To apply them to another Project, choose *Load Preferences from File* and locate the file you created.

=== Customizing Your Toolbar

One trick you can apply right away is to customize your toolbar to show icons for your favorite features. _Ctrl-click_ the Toolbar and choose *Customize Toolbar*. Now you can click and drag icons onto the Toolbar for easy access.

You can also remove any unwanted icons by dragging them away.

The number of icons you can add to your Toolbar depends on the width of your screen. If any aren’t visible, click the arrows to display them.

[screenshot: toolbar arrows ]

I have icons for Backing Up, taking a Snapshot, and my Project Word Count. These are actions I might only take once during a session, so I’m unlikely to remember the keyboard shortcuts.
