== Conclusion

We've reached the end of our Scrivener adventure. It'll take you a while to get the hang of all the Scrivener features, so go slowly. Don’t try to use everything at once. Maybe just pick a couple of features you want to try first and focus on those. Once you’re feeling more confident, add in a few more. Before you know it, you’ll be a Scrivener gladiator. Then I'll be coming to you for advice.

Although we’ve only covered a fraction of Scrivener's functionality, hopefully that’s been enough to get you started. It took me a year or so to get really confident with Scrivener. Even now, I often have to look something up or I realize there’s a much better way of doing things. Despite those challenges, I feel sure it’ll make your writing life much easier.

Everyone uses Scrivener in a different way. Some are happy with just 20% of the features, while others are intent on squeezing out every tiny possibility. Either way is fine. Software should be serving _you_, rather than the other way around.

Thanks so much for reading my book. Wishing you all the very best with your writing adventures.