version: 2.1
# use the AWS orb
orbs: 
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  # this section is generating the EPUB with AsciiDoctor
  build:
    docker:
      - image: cimg/ruby:2.7.4
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: AsciiDoctor build
          command: asciidoctor-epub3 -D output 1-introduction.adoc
      - persist_to_workspace:
          root: ./
          paths:
            - _output
  # this section uploads the site to S3
  deploy:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - attach_workspace:
          at: ./
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: _site
          to: 's3://www.catherinepope.com'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: _site
          to: 's3://www.catherinepope.com'
          
workflows:
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
